apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret 
type: Opaque # key value secret type
# Other secret types can be TLS where a certificate is used.
data:
  # Don't commit the passwords in practice even though they are Base64 "encoded" (not encrypted)
  # Also do not forget to add them on the machine you are using to deploy the cluster
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=